- _Sidebar.md
Needed for website to work properly
> Fix path to home

- GPU-Particles.md
h3d.parts.GpuParticles has no field add
> Fix method call

- Materials.md
Sources:
* https://heaps.io/documentation/materials.html
> Fix code snipet error in Materials doc

- Home.md
Just a quick update if I may, since the navigation menu is on the left of that text.
Also updated the first sentence to not repeat "designed".
Sources:
* https://heaps.io/documentation/home.html
> Update: Home

- Resource-Management.md
Sources:
* https://heaps.io/documentation/resource-management.html
> Update: Resource management

- H2D-Introduction.md
Fixed grammar in Scene Description
Sources:
* https://heaps.io/documentation/h2d-introduction.html
> Update: Introduction Scene Wording

- PBR-Materials.md
Little fix in the PBR example code to make it compile whith heaps 1.6.1
> Fixed function name in PBR doc

- H3D-Render-Targets.md
- _Sidebar.md
First attempt at writing documentation, so feedback welcome.
I would have liked to add an image or two, but they don't appear to be in the repo so it's not clear where to submit them.
> Add Render Target docs

- Installation.md
VScode restart not needed since v1.31
> Update: Installation

- Resource-Management.md
Live update is pretty useful feature, which is barely covered but can help tremendously during development. Gotta cover that at least to some extent.
Also added mp3/ogg support information.
> Add live-update draft docs

- H2D-Introduction.md
Sources:
* https://heaps.io/documentation/h2d-introduction.html
> Update: Introduction: Fix Spelling

- Resource-Baking.md
Sources:
* https://heaps.io/documentation/resource-baking.html
> Update: Resource Baking

- H2D-Introduction.md
- Hello-HashLink.md
- Hello-World.md
- Home.md
- Installation.md
After having experimented for a couple of months with Heaps and realizing, when recommending this great engine to a friend of mine, that the documentation was not really adapted to newbies and that most things I knew I had figured out by reading the source, I decided to try to update some of the documentation to help new users start up with Heaps.
I upgraded the installation file, which still mentionned Haxe 4 as a release candidate, and expanded on some vscode and extension concepts for those who might not have used the IDE yet.
The Hello-Hashlink tutorial never really worked for me so I refactored it a bit to include how I start new projects. I also had to update Hello-World (the javascript target) to fit with it. Hello-Hasklink is not a bit more standalone, but I still list the changes …
> Proposed modifications to installation, hello world examples and h2d introduction

- Hello-World.md
Adding the # comments inline in the `compile.hxml` file cause errors on launching debug if you just copied and pasted the snippet:-
```
Error: : unknown option '-debug				#'.
Did you mean:
--debug   add debug information to the compiled code
```
Sources:
* https://heaps.io/documentation/hello-world.html
> Update: Hello World

- Filters.md
Fix wrong code.
Sources:
* https://heaps.io/documentation/filters.html
> Update: Filters

- Installation.md
> Adding actual commands (recently did this step)

- Hello-HashLink.md
My first time through this I got hung up on this!!  Need to remove comments, I placed them outside the code block.  Smoother now
> Issue: Comments not allowed on same line in hxml

- H2D-Events-and-Interactivity.md
https://github.com/HeapsIO/heaps/issues/943
> Document hxd.System.getValue(IsTouch)

- DomKit.md
Correct some typos in Heaps Components (Domkit) doc.
Merry Christmas 🎁 !
> Correct some typos in DomKit doc

- Animation.md
I added what I think would be a common usage of animation. It shows how to load a spritesheet and convert it to a tile array using the `grid()` method, and then how to pass that array into the animation.
> added animation example using the grid method

- Drawable.md
Sources:
* https://heaps.io/documentation/drawable.html
> Fix typo in word "substracted"

- Text.md
Sources:
* https://heaps.io/documentation/text.html
> Update: Displaying text (BMFont)

- Drawing-Tiles.md
Huge overhaul here, apart from obvious typos. Better than filing a dozen PRs.
> Update Drawing-Tiles.md for readability and grammar

- H2D-Introduction.md
Simple change, adds a note that links to the Resource Management docs page.
Resolves #54
> Update: Introduction (Resource Initialization)

- First-outlook.md
- Installation.md
**Description**:
Updated **Installation** and **First Look** pages.
> Updated Getting Started sections.

- _Sidebar.md
Description:
We removed this page, but we forgot to update the sidebar. Woops!
> Updated sidebar

- First-outlook.md
> Typo fixes
